export const ROLES = {
  ADMINISTRATOR: 'ADMINISTRATOR',
  WAREHOUSE_MANAGER: 'WAREHOUSE_MANAGER',
  QC_STAFF: 'QC_STAFF',
  OPERATION_STAFF: 'OPERATION_STAFF',
  SUPPLIER: 'SUPPLIER',
  DISTRIBUTOR: 'DISTRIBUTOR',
} as const

export type Role = (typeof ROLES)[keyof typeof ROLES]
