import { useNavigate } from 'react-router'
import AppIcon from '@/components/common/AppIcon'
import type { RoleDashboardConfig } from './roleDashboardConfig'

const tone={green:'bg-emerald-50 text-emerald-700',orange:'bg-orange-50 text-orange-600',blue:'bg-sky-50 text-sky-700',red:'bg-red-50 text-red-600'}

export default function RoleDashboard({config,primaryActionRoute}:{config:RoleDashboardConfig;primaryActionRoute?:string}){
 const navigate = useNavigate()
 return <div className="mx-auto max-w-[1600px] space-y-5">
  <div className="flex flex-col justify-between gap-4 xl:flex-row xl:items-end"><div><p className="text-sm font-medium text-emerald-700">{config.eyebrow}</p><h1 className="mt-1 text-2xl font-bold sm:text-3xl">{config.title}</h1><p className="mt-1 text-sm text-slate-500">{config.description}</p></div><button type="button" onClick={primaryActionRoute ? () => navigate(primaryActionRoute) : undefined} className="inline-flex h-10 w-fit items-center gap-2 rounded-lg bg-emerald-700 px-4 text-sm font-semibold text-white hover:bg-emerald-800"><AppIcon name="plus" className="size-4"/>{config.primaryAction}</button></div>
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{config.stats.map(s=><article key={s.label} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><span className={`grid size-10 place-items-center rounded-lg ${tone[s.tone]}`}><AppIcon name={s.icon} className="size-5"/></span><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${tone[s.tone]}`}>{s.note}</span></div><p className="mt-4 text-[11px] font-bold uppercase text-slate-500">{s.label}</p><p className="mt-1 text-2xl font-bold text-slate-950">{s.value}</p></article>)}</div>
  <div className="grid gap-5 xl:grid-cols-[minmax(0,1.5fr)_minmax(320px,1fr)]"><section className="rounded-xl border border-slate-200 bg-white shadow-sm"><header className="flex items-center justify-between p-5"><h2 className="text-sm font-bold">Công việc cần xử lý</h2><button className="text-xs font-semibold text-emerald-700">Xem tất cả</button></header><div className="divide-y divide-slate-100 px-5">{config.tasks.map((t,i)=><div key={t.title} className="flex items-center gap-3 py-4"><span className="grid size-10 shrink-0 place-items-center rounded-lg bg-emerald-50 text-emerald-700"><AppIcon name={i===0?'clipboard':i===1?'pending':'package'} className="size-5"/></span><div className="min-w-0"><h3 className="truncate text-sm font-semibold">{t.title}</h3><p className="truncate text-xs text-slate-500">{t.description}</p></div><span className="ml-auto hidden rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-bold text-slate-600 sm:block">{t.status}</span></div>)}</div></section><section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-sm font-bold">Trạng thái hệ thống</h2><div className="mt-8 flex flex-col items-center"><div className="relative grid size-36 place-items-center rounded-full bg-[conic-gradient(#059669_0_82%,#e2e8f0_82%_100%)]"><div className="grid size-28 place-items-center rounded-full bg-white text-center"><span><b className="block text-2xl">82%</b><small className="text-slate-500">Hoàn thành</small></span></div></div><p className="mt-6 text-center text-sm text-slate-500">Dữ liệu minh họa cho khung FE. Sẽ thay bằng API theo nghiệp vụ.</p></div></section></div>
 </div>
}
