import { ROLES, type Role } from '@/constants/roles'
import type { ComponentProps } from 'react'
import type AppIcon from '@/components/common/AppIcon'

export type IconName = ComponentProps<typeof AppIcon>['name']
export interface RoleDashboardConfig {
  roleLabel: string
  eyebrow: string
  title: string
  description: string
  primaryAction: string
  menu: ReadonlyArray<{ label: string; icon: IconName }>
  stats: ReadonlyArray<{ label: string; value: string; note: string; icon: IconName; tone: 'green'|'orange'|'blue'|'red' }>
  tasks: ReadonlyArray<{ title: string; description: string; status: string }>
}

const commonDashboard={label:'Bảng điều khiển',icon:'dashboard' as const}
export const roleDashboardConfigs: Record<Exclude<Role,'ADMINISTRATOR'>,RoleDashboardConfig> = {
 [ROLES.WAREHOUSE_MANAGER]:{roleLabel:'Quản lý kho',eyebrow:'Điều hành kho',title:'Tổng quan kho hàng',description:'Theo dõi tồn kho, sức chứa và các yêu cầu cần phê duyệt.',primaryAction:'Tạo báo cáo',menu:[commonDashboard,{label:'Tồn kho',icon:'database'},{label:'Lô hàng',icon:'package'},{label:'Phê duyệt',icon:'clipboard'},{label:'Cảnh báo',icon:'alert'},{label:'Báo cáo',icon:'download'}],stats:[{label:'Khối lượng tồn kho',value:'8,500 kg',note:'68% sức chứa',icon:'database',tone:'green'},{label:'Lô chờ nhập',value:'12',note:'Cần duyệt',icon:'package',tone:'orange'},{label:'Vị trí đang dùng',value:'24/36',note:'Còn 12 vị trí',icon:'dashboard',tone:'blue'},{label:'Cảnh báo',value:'03',note:'Cần xử lý',icon:'alert',tone:'red'}],tasks:[{title:'Duyệt lô BATCH-DEMO-001',description:'Nhà cung cấp Nông sản Xanh',status:'Chờ duyệt'},{title:'Kiểm tra sức chứa kho mát C',description:'Mức sử dụng đạt 82%',status:'Hôm nay'},{title:'Xem báo cáo tồn kho tuần',description:'Kỳ báo cáo 09/2026',status:'Mới'}]},
 [ROLES.QC_STAFF]:{roleLabel:'Nhân viên kiểm định',eyebrow:'Kiểm soát chất lượng',title:'Công việc kiểm định',description:'Quản lý lô chờ QC, kết quả kiểm tra và bằng chứng chất lượng.',primaryAction:'Bắt đầu kiểm định',menu:[commonDashboard,{label:'Lô chờ kiểm định',icon:'pending'},{label:'Phiếu kiểm định',icon:'clipboard'},{label:'Bằng chứng',icon:'scan'},{label:'Tiêu chuẩn QC',icon:'shield'}],stats:[{label:'Chờ kiểm định',value:'08',note:'2 ưu tiên',icon:'pending',tone:'orange'},{label:'Hoàn thành hôm nay',value:'15',note:'+3 so với hôm qua',icon:'clipboard',tone:'green'},{label:'Đạt chất lượng',value:'92%',note:'Trong 30 ngày',icon:'shield',tone:'blue'},{label:'Lô không đạt',value:'02',note:'Cần báo cáo',icon:'alert',tone:'red'}],tasks:[{title:'Kiểm định BATCH-DEMO-002',description:'Khoai tây Đà Lạt loại 1',status:'Ưu tiên'},{title:'Bổ sung hình ảnh kiểm định',description:'Phiếu QC-2026-015',status:'Thiếu dữ liệu'},{title:'Xác nhận kết quả phòng lab',description:'Phiếu QC-2026-014',status:'Chờ ký'}]},
 [ROLES.OPERATION_STAFF]:{roleLabel:'Nhân viên vận hành',eyebrow:'Vận hành kho',title:'Công việc vận hành',description:'Theo dõi nhập, xuất, chuyển vị trí và điều chỉnh tồn kho.',primaryAction:'Tạo phiếu nhập',menu:[commonDashboard,{label:'Nhập kho',icon:'package'},{label:'Xuất kho',icon:'logout'},{label:'Chuyển kho',icon:'pending'},{label:'Điều chỉnh tồn',icon:'clipboard'},{label:'Quét QR',icon:'scan'}],stats:[{label:'Phiếu nhập hôm nay',value:'12',note:'4 đang xử lý',icon:'package',tone:'green'},{label:'Phiếu xuất hôm nay',value:'09',note:'2 chờ lấy hàng',icon:'logout',tone:'orange'},{label:'Lệnh chuyển vị trí',value:'05',note:'Trong ca',icon:'pending',tone:'blue'},{label:'Sai lệch tồn kho',value:'01',note:'Cần đối soát',icon:'alert',tone:'red'}],tasks:[{title:'Nhập kho lô BATCH-DEMO-003',description:'Vị trí đề xuất C-R02-B01',status:'Chờ nhập'},{title:'Chuẩn bị đơn xuất ORD-2026-018',description:'5 mặt hàng · 420 kg',status:'Đang lấy'},{title:'Chuyển lô sang kho mát C',description:'Từ A-R01-B01',status:'Trong ca'}]},
 [ROLES.SUPPLIER]:{roleLabel:'Nhà cung cấp',eyebrow:'Cổng nhà cung cấp',title:'Tổng quan lô hàng',description:'Khai báo lô nông sản và theo dõi tiến độ kiểm định, nhập kho.',primaryAction:'Khai báo lô mới',menu:[commonDashboard,{label:'Lô hàng của tôi',icon:'package'},{label:'Khai báo lô',icon:'plus'},{label:'Chứng nhận',icon:'shield'},{label:'Thông báo',icon:'bell'},{label:'Hồ sơ doanh nghiệp',icon:'users'}],stats:[{label:'Tổng lô đã khai báo',value:'24',note:'Trong năm nay',icon:'package',tone:'green'},{label:'Chờ duyệt',value:'03',note:'Đang xử lý',icon:'pending',tone:'orange'},{label:'Đã nhập kho',value:'18',note:'75% tổng lô',icon:'database',tone:'blue'},{label:'Cần bổ sung',value:'01',note:'Thiếu chứng từ',icon:'alert',tone:'red'}],tasks:[{title:'Bổ sung giấy chứng nhận',description:'Lô BATCH-DEMO-001',status:'Cần làm'},{title:'Theo dõi kiểm định',description:'Lô BATCH-DEMO-002 đang chờ QC',status:'Đang xử lý'},{title:'Cập nhật hồ sơ vùng trồng',description:'Vùng trồng Đà Lạt',status:'Sắp hết hạn'}]},
 [ROLES.DISTRIBUTOR]:{roleLabel:'Nhà phân phối',eyebrow:'Cổng nhà phân phối',title:'Tổng quan đơn hàng',description:'Tạo đơn mua, theo dõi phê duyệt, chuẩn bị và giao hàng.',primaryAction:'Tạo đơn hàng',menu:[commonDashboard,{label:'Đơn hàng của tôi',icon:'clipboard'},{label:'Tạo đơn hàng',icon:'plus'},{label:'Theo dõi giao hàng',icon:'package'},{label:'Truy xuất nguồn gốc',icon:'scan'},{label:'Hồ sơ doanh nghiệp',icon:'users'}],stats:[{label:'Tổng đơn hàng',value:'36',note:'Trong năm nay',icon:'clipboard',tone:'green'},{label:'Chờ xác nhận',value:'04',note:'Đang xử lý',icon:'pending',tone:'orange'},{label:'Đang giao',value:'06',note:'Theo dõi',icon:'package',tone:'blue'},{label:'Thanh toán quá hạn',value:'01',note:'Cần xử lý',icon:'alert',tone:'red'}],tasks:[{title:'Xác nhận đơn ORD-2026-021',description:'1,200 kg Gạo ST25',status:'Chờ xác nhận'},{title:'Theo dõi giao hàng',description:'Đơn ORD-2026-018',status:'Đang giao'},{title:'Cập nhật hồ sơ công ty',description:'Thông tin người liên hệ',status:'Cần làm'}]},
}

export const adminMenu=[commonDashboard,{label:'Người dùng',icon:'users'},{label:'Vai trò & quyền',icon:'shield'},{label:'Loại nông sản',icon:'package'},{label:'Tiêu chuẩn kiểm định',icon:'clipboard'},{label:'Nhật ký hệ thống',icon:'scan'},{label:'Cài đặt',icon:'settings'}] as const
export const roleLabels:Record<Role,string>={[ROLES.ADMINISTRATOR]:'Quản trị viên',[ROLES.WAREHOUSE_MANAGER]:'Quản lý kho',[ROLES.QC_STAFF]:'Nhân viên kiểm định',[ROLES.OPERATION_STAFF]:'Nhân viên vận hành',[ROLES.SUPPLIER]:'Nhà cung cấp',[ROLES.DISTRIBUTOR]:'Nhà phân phối'}
