import AppIcon from '@/components/common/AppIcon'
import { dashboardStats, pendingTasks, recentActivities, roleDistribution, weekLabels, weeklyActivity } from '@/features/admin-dashboard/dashboardData'

const tones={green:'bg-emerald-50 text-emerald-700',orange:'bg-orange-50 text-orange-600',blue:'bg-sky-50 text-sky-700',red:'bg-red-50 text-red-600'}
const badges={red:'bg-red-50 text-red-600',orange:'bg-orange-50 text-orange-600',neutral:'bg-slate-100 text-slate-600'}

function Panel({title,action,children,className=''}:{title:string;action?:React.ReactNode;children:React.ReactNode;className?:string}){
 return <section className={`rounded-xl border border-slate-200 bg-white shadow-sm ${className}`}><header className="flex items-center justify-between px-5 pt-5"><h2 className="text-sm font-bold">{title}</h2>{action}</header>{children}</section>
}

function ActivityChart(){
 const points=weeklyActivity.map((v,i)=>`${i*(100/(weeklyActivity.length-1))},${100-v}`).join(' ')
 return <div className="px-5 pb-5 pt-6"><div className="relative h-52 sm:h-64"><div className="absolute inset-0 flex flex-col justify-between">{[100,75,50,25,0].map(n=><div key={n} className="border-t border-dashed border-slate-200"><span className="-translate-y-2.5 bg-white pr-2 text-[10px] text-slate-400">{n}</span></div>)}</div><svg className="absolute inset-0 h-full w-full overflow-visible" viewBox="0 0 100 100" preserveAspectRatio="none" aria-label="Biểu đồ hoạt động 7 ngày"><defs><linearGradient id="chartFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#10b981" stopOpacity=".22"/><stop offset="1" stopColor="#10b981" stopOpacity="0"/></linearGradient></defs><polygon points={`0,100 ${points} 100,100`} fill="url(#chartFill)"/><polyline points={points} fill="none" stroke="#059669" strokeWidth="2" vectorEffect="non-scaling-stroke"/>{weeklyActivity.map((v,i)=><circle key={i} cx={i*(100/(weeklyActivity.length-1))} cy={100-v} r="1.5" fill="white" stroke="#059669" strokeWidth=".7" vectorEffect="non-scaling-stroke"/>)}</svg></div><div className="mt-3 grid grid-cols-7 text-center text-[11px] font-medium text-slate-500">{weekLabels.map(d=><span key={d}>{d}</span>)}</div></div>
}

export default function AdminDashboardPage(){return <div className="mx-auto max-w-[1600px] space-y-5">
 <div className="flex flex-col justify-between gap-4 xl:flex-row xl:items-end"><div><p className="text-sm font-medium text-emerald-700">Tổng quan hệ thống</p><h1 className="mt-1 text-2xl font-bold sm:text-3xl">Bảng điều khiển</h1><p className="mt-1 text-sm text-slate-500">Theo dõi tình trạng hệ thống và các công việc cần xử lý.</p></div><div className="flex flex-wrap gap-2"><button className="inline-flex h-10 items-center gap-2 rounded-lg bg-emerald-700 px-4 text-sm font-semibold text-white hover:bg-emerald-800"><AppIcon name="plus" className="size-4"/>Tạo mới</button><button className="inline-flex h-10 items-center gap-2 rounded-lg border border-slate-300 bg-white px-4 text-sm font-semibold text-slate-700"><AppIcon name="download" className="size-4"/>Xuất báo cáo</button><button className="inline-flex h-10 items-center gap-2 rounded-lg border border-slate-300 bg-white px-4 text-sm font-semibold text-slate-700"><AppIcon name="scan" className="size-4"/>Quét QR</button></div></div>
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{dashboardStats.map(s=><article key={s.label} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><span className={`grid size-10 place-items-center rounded-lg ${tones[s.tone]}`}><AppIcon name={s.icon} className="size-5"/></span><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${tones[s.tone]}`}>{s.note}</span></div><p className="mt-4 text-[11px] font-bold uppercase text-slate-500">{s.label}</p><p className={`mt-1 text-3xl font-bold ${s.tone==='red'?'text-red-600':'text-slate-950'}`}>{s.value}</p></article>)}</div>
 <div className="grid gap-5 xl:grid-cols-[minmax(0,2fr)_minmax(320px,1fr)]"><Panel title="Hoạt động hệ thống (7 ngày)" action={<select className="rounded-lg border border-slate-200 px-3 py-2 text-xs text-slate-600"><option>Tất cả hoạt động</option></select>}><ActivityChart/></Panel><Panel title="Phân bổ người dùng"><div className="flex min-h-72 flex-col items-center justify-center p-5"><div className="relative size-36 rounded-full" style={{background:'conic-gradient(#087f5b 0 45%,#6366f1 45% 75%,#14b8a6 75% 100%)'}}><div className="absolute inset-4 grid place-items-center rounded-full bg-white text-center"><span><b className="block text-2xl">100%</b><small className="text-slate-500">Tài khoản</small></span></div></div><div className="mt-6 w-full space-y-3">{roleDistribution.map(x=><div key={x.label} className="flex items-center text-xs"><span className="mr-2 size-2.5 rounded-full" style={{background:x.color}}/><span className="text-slate-600">{x.label}</span><b className="ml-auto">{x.value}%</b></div>)}</div></div></Panel></div>
 <div className="grid gap-5 xl:grid-cols-[minmax(0,1.5fr)_minmax(340px,1fr)]"><Panel title="Công việc cần xử lý" action={<button className="text-xs font-semibold text-emerald-700">Xem tất cả</button>}><div className="divide-y divide-slate-100 px-5 py-2">{pendingTasks.map((t,i)=><div key={t.title} className="flex items-center gap-3 py-4"><span className="grid size-10 shrink-0 place-items-center rounded-lg bg-emerald-50 text-emerald-700"><AppIcon name={i===0?'users':i===1?'clipboard':'shield'} className="size-5"/></span><div className="min-w-0"><h3 className="truncate text-sm font-semibold">{t.title}</h3><p className="truncate text-xs text-slate-500">{t.description}</p></div><span className={`ml-auto hidden rounded-full px-2.5 py-1 text-[10px] font-bold sm:block ${badges[t.tone]}`}>{t.badge}</span></div>)}</div></Panel><Panel title="Hoạt động gần đây"><div className="px-5 py-3">{recentActivities.map((a,i)=><div key={a.title} className="relative flex gap-3 pb-5 last:pb-1">{i<recentActivities.length-1&&<span className="absolute left-[15px] top-8 h-[calc(100%-24px)] w-px bg-slate-200"/>}<span className={`z-10 grid size-8 shrink-0 place-items-center rounded-full ${tones[a.tone]}`}><AppIcon name={a.tone==='red'?'alert':'pending'} className="size-4"/></span><div><h3 className="text-sm font-semibold">{a.title}</h3><p className="mt-0.5 text-xs leading-5 text-slate-500">{a.description}</p><time className="mt-1 block text-[10px] text-slate-400">{a.time}</time></div></div>)}</div></Panel></div>
</div>}
