import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router'
import AppIcon from '@/components/common/AppIcon'
import { ROUTES } from '@/constants/routes'
import { getAuthErrorMessage } from '@/services/authService'
import { getInspectionStandards, type InspectionStandardListItem } from '@/services/inspectionStandardService'

export default function InspectionStandardListPage(){
 const navigate=useNavigate(),[items,setItems]=useState<InspectionStandardListItem[]>([]),[search,setSearch]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('')
 const load=async(query='')=>{setLoading(true);setError('');try{setItems(await getInspectionStandards(query))}catch(e){setError(getAuthErrorMessage(e,'Không thể tải danh sách tiêu chuẩn kiểm định.'))}finally{setLoading(false)}}
 useEffect(()=>{void getInspectionStandards().then(setItems).catch(e=>setError(getAuthErrorMessage(e,'Không thể tải danh sách tiêu chuẩn kiểm định.'))).finally(()=>setLoading(false))},[])
 return <div className="mx-auto max-w-[1600px] space-y-5"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-wider text-emerald-700">Quản trị · Kiểm định</p><h1 className="mt-1 text-2xl font-bold sm:text-3xl">Tiêu chuẩn kiểm định</h1><p className="mt-1 text-sm text-slate-500">Quản lý các bộ tiêu chuẩn và phiên bản áp dụng cho nông sản.</p></div><button onClick={()=>navigate(ROUTES.ADMIN_INSPECTION_STANDARD_NEW)} className="inline-flex h-10 items-center gap-2 rounded-lg bg-emerald-700 px-4 text-sm font-semibold text-white"><AppIcon name="plus" className="size-4"/>Thêm tiêu chuẩn kiểm định</button></div>{error&&<p className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-100 p-4 sm:flex-row sm:items-center sm:justify-between"><h2 className="font-bold">Danh sách bộ tiêu chuẩn <span className="text-slate-400">({items.length})</span></h2><div className="flex gap-2"><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void load(search)}} placeholder="Tìm mã hoặc tên..." className="h-9 rounded-lg border border-slate-200 px-3 text-sm"/><button onClick={()=>void load(search)} className="h-9 rounded-lg border border-slate-300 px-3 text-sm font-semibold">Tìm</button></div></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-[11px] uppercase text-slate-500"><tr><th className="px-5 py-3">Mã</th><th className="px-5 py-3">Tên tiêu chuẩn</th><th className="px-5 py-3">Loại nông sản</th><th className="px-5 py-3">Phiên bản</th><th className="px-5 py-3">Tiêu chí</th><th className="px-5 py-3">Trạng thái</th></tr></thead><tbody className="divide-y divide-slate-100">{loading?<tr><td colSpan={6} className="p-8 text-center text-slate-500">Đang tải dữ liệu...</td></tr>:items.length===0?<tr><td colSpan={6} className="p-8 text-center text-slate-500">Chưa có bộ tiêu chuẩn kiểm định.</td></tr>:items.map(item=><tr key={item.id} className="hover:bg-slate-50"><td className="px-5 py-4 font-mono text-xs font-bold text-emerald-700">{item.code}</td><td className="px-5 py-4 font-semibold">{item.name}</td><td className="px-5 py-4 text-slate-600">{item.cropTypeName}</td><td className="px-5 py-4">v{item.versionNo}.0</td><td className="px-5 py-4">{item.criterionCount}</td><td className="px-5 py-4"><span className="rounded-full bg-amber-50 px-2.5 py-1 text-[10px] font-bold text-amber-700">{item.status==='DRAFT'?'Bản nháp':item.status}</span></td></tr>)}</tbody></table></div></section></div>
}
